#build the project from the docker hub image

name: letterboxd-bluesky-poster

services:
  letterboxd-bluesky-poster:
    container_name: "letterboxd-bluesky-poster"
    image: finiteui/letterboxd-bluesky-poster:latest
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - letterboxd-bluesky-poster-data:/app/Data

volumes:
  letterboxd-bluesky-poster-data: